name: drawing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.gif
    - assets/group.jpg
    - assets/1.jpg
    - assets/2.jpg   
    - assets/3.jpg
    - assets/4.jpg   
    - assets/5.jpg
    - assets/6.jpg   
    - assets/7.jpg
    - assets/8.jpg   
    - assets/9.jpg
    - assets/10.jpg   
    - assets/11.jpg
    - assets/12.jpg   
    - assets/13.jpg
    - assets/14.jpg   
    - assets/15.jpg
    - assets/16.jpg   
    - assets/17.jpg
    - assets/18.jpg   
    - assets/19.jpg
    - assets/20.jpg   
